### PR TITLE
Snyk consolidated findings

### LINKED ISSUE #1616: Snyk Parser should consolidate findings better
2020-10-27 13_08_00-Window

Currently the Snyk parser does not consolidate findings correctly. This results in an enormous amount of warnings. 

The number of warnings should be equal to the number of top-level packages that need to be updated not the total amount of vulnerabilities

### PR DESCRIPTION
**Pull request by bdtesty**
Closes #1616.

### CODE REVIEW

**Comment by bdtesty** [comment]
@fniessink Can you help with this ? I'm not sure whether I should address the Travis and Deepsource issues or not.  

Local unit tests were 100% ok.

**Comment by fniessink** [comment]
I'll take a look as soon as possible (this weekend probably). Can you turn on collaboration mode on your branch?

**Comment by bdtesty** [comment]
> I'll take a look as soon as possible (this weekend probably). Can you turn on collaboration mode on your branch?

Thanks ! 

I think you already have collab access for my branch https://github.com/greckko/quality-time/tree/snyk_consolidated_findings

**Comment by fniessink** [comment]
@greckko The code was a bit hard to follow. I decided to take a different approach and group the leaf dependencies instead of the direct dependencies because the lead dependencies are the ones with the security warning(s). What do you think?

**Comment by bdtesty** [comment]
> @greckko The code was a bit hard to follow. I decided to take a different approach and group the leaf dependencies instead of the direct dependencies because the lead dependencies are the ones with the security warning(s). What do you think?

Did you manage to get the same result ? https://github.com/ICTU/quality-time/issues/1616#issuecomment-721284898

For example the vulnerable leaf depedendency 'ajv' is part of  laravel-mix@4.0.16 which also contains many more vulnerabilities. resulting in many warnings. (normally a big json snyk report)

A developer only needs to know that laravel-mix@4.0.16 is outdated and contains many vulnerabilities (such as ajv) resulting in less warnings and is more digestable for a developer to review and fix.

I do agree my code is a bit hard to follow and I should have made a few seperate methods instead of lots of local variables/for loops inside 1 method.

**Comment by bdtesty** [comment]
@fniessink snyk test reports
[snyk_test_reports.zip](https://github.com/ICTU/quality-time/files/5536287/snyk_test_reports.zip)

**Pull request merged**
