### PR TITLE
2961 split server in two

### PR DESCRIPTION
**Pull request by emdv88**

### CODE REVIEW

**Comment by emdv88** [comment]
Not all tests pass yet, but we're getting there. So I think a review might already be helpful. Some things that I still don't understand:

- building the docs fails because for some reason it doesn't find the shared_python directory
- deepsource requires an audit, but I don't know how to do that
- collecting coverage report over both internal and external server for the feature tests

Other than that, the application tests still fail so i guess something is still wrong. And some unittests need to be added to the shared_python module for complete coverage.

**Comment by emdv88** [comment]
Ah and it seems that sounarcloud forgot all issues that were ignored or marked as false positive, so that will still need to be fixed aswell.

**Comment by fniessink** [comment]
This seems relevant: https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/?utm_campaign=2022-05-03-brnd-dockerfilemultiplebuildcontexts&utm_medium=social&utm_source=twitter

**Comment by fniessink** [comment]
Implemented via other PRs.

**Pull request closed without merging**
