### PR TITLE
Make source links open in a new window

### LINKED ISSUE #1203: Feature request: open source links in new window/tab
Opening source links in the same window will, when returning to QT using the back-button, result in coming back to the main QT screen. This means losing the focus of your work.

I added a PR #1202 for this issue.

### PR DESCRIPTION
**Pull request by Erik-Stel**
Opening source links in the same window will, when returning to QT using the back-button, result in coming back to the main QT screen. This means losing the focus of your work.

### CODE REVIEW

**Review by fniessink — CHANGES_REQUESTED** [review]
Don't forget to update the docs/CHANGELOG.md

**Comment by Erik-Stel** [comment]
Did update Changelog. Assumed you meant to have a new version. Feel free to add more fixes/updates to this version of course ;-).

**Review by fniessink — CHANGES_REQUESTED** [review]
You need to have a "## [Unreleased]" header, like it says on line 10 of the CHANGELOG.md. The release script will replace it with the correct version and date.

**Comment by Erik-Stel** [comment]
My bad...changed the changelog again.

**Pull request merged**
