### PR TITLE
Prevent summary card labels from overflowing

### PR DESCRIPTION
**Pull request by Erik-Stel**
This change clips labels and adds ellipsis to show the fact that content is clipped.
Added a title to the HTML element to allow user to see full name by hovering the card label (in most browsers).

### CODE REVIEW

**Comment by Erik-Stel** [comment]
It looks like the SonarQube environment within CI pipeline is not setup correctly. Issue does not seem related to changed code.

**Comment by fniessink** [comment]
Thanks! Sonarqube analysis isn't allowed on forks; it's supposed to be possible though: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by fniessink** [comment]
I've turned on the Sonarcloud analysis for PR's from forks. Can you please rebase (NOT merge) on top of master? Thanks.

**Comment by fniessink** [comment]
> I've turned on the Sonarcloud analysis for PR's from forks. Can you please rebase (NOT merge) on top of master? Thanks.

Strike that. Running workflows with secrets on PR's from forks is deemed unsafe. The PR is small enough that I will risk merging it without a Sonarcloud analysis :-)

**Pull request merged**
